### ISSUE TITLE
Unable to resolve configuration with compilerPath

### ISSUE THREAD

**Issue by ghost** [Alex079/vscode-avr-helper#19] opened 2021-10-02 14:53 UTC
Hi Alex,
First of all I would like to thank your effort on this plugin as I like how it works. I am working with a Windows 10(21h1) environment with WinAVR ver20090313 installed. Originally I use Eclipse C/C++ IDE for building and burning codes on my ATmega32. I like VS Code as I include all my compilers in one place for ease of use so I tried using it for AVR, your plugin looks the simple to use in terms of UI. However I want build a very simple .c file where I just include <avr/io.h> and nothing is running in main method. I ran the code it manages to identify the included libraries correctly but it keeps throwing these errors in the TERMINAL:

> > Executing task: make -fc:\Amir\Coding\VSTest\.vscode\avr.targets.mk build <
/usr/bin/sh: c:AmirSoftwaresWinAVRbinavr-gcc.exe: command not found
/usr/bin/sh: c:AmirSoftwaresWinAVRbinavr-gcc.exe: command not found
/usr/bin/sh: c:AmirSoftwaresWinAVRbinavr-gcc.exe: command not found
/usr/bin/sh: c:AmirSoftwaresWinAVRbinavr-gcc.exe: command not found
===== Making .vscode/avr.build/obj/main.c.o
mkdir: cannot create directory `.vscode\\avr.build\\obj': File exists
make: [.vscode/avr.build/obj/main.c.o] Error 1 (ignored)
/usr/bin/sh: c:AmirSoftwaresWinAVRbinavr-gcc.exe: command not found
make: *** [.vscode/avr.build/obj/main.c.o] Error 127
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command make -fc:\Amir\Coding\VSTest\.vscode\avr.targets.mk build" terminated with exit code: 1.
Terminal will be reused by tasks, press any key to close it. 

The WinAVR is installed at C:\Amir\Softwares\

However I noticed in the OUTPUT:

>[02/10/2021, 15:47:46] Unable to resolve configuration with compilerPath "c:\Amir\Softwares\WinAVR\bin\avr-gcc.exe".  Using "C:\Amir\Softwares\MinGW\mingw32\bin\gcc.exe" instead.

it  popped out the moment I selected the Device type and frequency (ATmega32 and 16000000) I am sure that the avr-gcc is the selected path at least from what I can see in "Edit Configuration (UI)" and the "c_cpp_properties.json" file.
I uninstalled MinGW it became:
>[02/10/2021, 15:47:46] Unable to resolve configuration with compilerPath "c:\Amir\Softwares\WinAVR\bin\avr-gcc.exe"
I tried reinstalling WinAVR to its default location but no luck.

I used your Makefile from #16 (https://raw.githubusercontent.com/Alex079/vscode-avr-helper/7d3a18e31cb2d8e802e6fe0fd27c918f30ab36ed/resources/windows/avr.targets.mk)
 But nothing changed all I could notice is that the number of these lines reduced:

 >/usr/bin/sh: c:AmirSoftwaresWinAVRbinavr-gcc.exe: command not found.

I just don't get why it refuses to change the complier, all commands work in the cmd (gcc, avr-gcc and make) but I did not try set a target for them. 
I did not identify the Upload Port and rate because yet I don't have any files in the avr/build.obj to flash.

my c_cpp_properties.json looks like this:
{
    "configurations": [
        {
            "name": "AVR",
            "intelliSenseMode": "${default}",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "c:\\Amir\\Softwares\\WinAVR\\bin\\avr-gcc.exe",
            "includePath": [
                "c:\\Amir\\Coding\\VSTest\\**",
                "c:\\Amir\\Softwares\\WinAVR\\avr\\**",
                "c:\\Amir\\Softwares\\WinAVR\\avr\\include\\**"
            ],
            "compilerArgs": [
                "-mmcu=atmega32        [c:\\amir\\softwares\\winavr\\bin\\avrdude.conf:6185]",
                "-DF_CPU=16000000UL"
            ]
        }
    ],
    "version": 4
}

Thanks in Advance

**Comment by Alex079** [comment] 2021-10-04 20:14
Hi!

I think this is caused by more verbose output of avrdude version bundled in winavr. The latest winavr I could find is from 2010-01-20.
You can try one of the following:

- install avr-gcc for windows
or
- update `AVR.device.type` setting in workspace settings or directly in `.vscode/settings.json` file to contain only `atmega32`

I hope it helps.

**Comment by DesertXGhost** [comment] 2021-10-04 21:02
Thanks for the response yes it helped at least I am not getting errors that the command is not found however I got another issues which is :
"make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again."

I tried running the "make command in both the cmd and the powershell and they ran fine, not sure if I should update my make
my GNU make version is 3.81

**Comment by Alex079** [comment] 2021-10-04 21:28
Is the `utils/bin` directory added to PATH environment variable?

**Comment by Alex079** [comment] 2021-10-04 22:49
For wrong `AVR.device.type`, I will prepare a fix for filtering avrdude output to support this version of avrdude.
Regarding the issues with `make` in Windows, there is a big piece of work to switch from make to node spawn. In general, it works but needs clear error handling and a lot of testing.

**Comment by DesertXGhost** [comment] 2021-10-05 09:04
> Is the `utils/bin` directory added to PATH environment variable?

Yes

**Comment by DesertXGhost** [comment] 2021-10-05 18:01
Oops I mange to make it build not sure how I will try to reproduce and close the issue

**Comment by Alex079** [comment] 2021-10-05 18:10
cool :slightly_smiling_face: 
In my test with WinAVR, avr-objdump in Windows still doesn't work as well mkdir and rmdir. I think my test setup is a bit broken by now.
I will release the patch version for avrdude output parsing anyway. Thank you!

**Comment by Alex079** [comment] 2021-10-05 19:33
It looks like `mkdir` and `rmdir` behave differently depending on the setup, I do not know yet what could cause this.
I suggest to do two things
- remove the unrecognized options from `avr.targets.mk` because the compiler in winavr does not like them
- replace `mkdir $(subst /,\,$(@D))` with `mkdir -p $(@D)` because "it works on my machine"

**Comment by DesertXGhost** [comment] 2021-10-05 19:44
I am stuck now too at avr-objdump

**Comment by Alex079** [comment] 2021-10-05 20:02
OK. At this point you can try flashing a chip, objdump is optional and needed for assembly code inspection.

**Comment by Alex079** [comment] 2021-10-07 19:49
I could reproduce this kind of error only when composing the command by hand and passing the same object file to linker twice in the same command. I am not sure that duplicated filename is the problem here though. May I ask you to check, please, if there is any indication of function duplication source in the error you got? If there is none, we can try running `make --trace -f .vscode\avr.targets.mk build`

**Comment by DesertXGhost** [comment] 2021-10-07 20:24
--trace in an unrecognized option

**Comment by Alex079** [comment] 2021-10-07 22:07
OK. I can suggest to try a version of the plugin version which does not use make. This one **is not** production ready. 
[vscode-avr-helper-0.0.0-preview.zip](https://github.com/Alex079/vscode-avr-helper/files/7307182/vscode-avr-helper-0.0.0-preview.zip)

**Comment by Alex079** [comment] 2022-09-05 19:51
released v2

**Closed by Alex079** 2022-09-05 19:51 UTC
